sylius_product_index_by_taxon:
    pattern: /categories/{permalink}
    defaults:
        _controller: HypebeastCoreBundle:Catalog:taxon

sylius_product_show:
    pattern: /brands/{brand}/{slug}
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            template: HypebeastWebBundle:Frontend/Product:show.html.twig
            criteria: {slug: $slug, status: %sylius.constant.product_status_published%}

store_back_in_stock:
    pattern: /back-in-stock
    defaults:
        _controller: HypebeastCoreBundle:Catalog:backInStock

store_new_arrivals:
    pattern: /new-arrivals
    defaults:
        _controller: HypebeastCoreBundle:Catalog:newArrival

store_sale:
    pattern: /sale
    defaults:
        _controller: HypebeastCoreBundle:Catalog:sale

store_sale_n_percent_off:
    pattern: /sale/{percentage}-percent-off
    defaults:
        _controller: HypebeastCoreBundle:Catalog:saleNPercentOff

store_search:
    pattern: /search
    defaults:
        _controller: HypebeastCoreBundle:Catalog:search

store_brands:
    pattern: /brands
    defaults:
        _controller: sylius.controller.taxonomy:showAction
        _sylius:
            template: HypebeastWebBundle:Frontend/Product:brands.html.twig
            criteria: {name: 'Brand'}

store_brand:
    pattern: /brands/{permalink}
    defaults:
        _controller: HypebeastCoreBundle:Catalog:taxon

store_category:
    pattern: /categories/{permalink}
    defaults:
        _controller: HypebeastCoreBundle:Catalog:taxon

store_subcategory:
    pattern: /categories/{parent}/{permalink}
    defaults:
        _controller: HypebeastCoreBundle:Catalog:taxon
